image:
  tag: "prod"

ingress:
  hosts:
    - host: api.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

rollout:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/managed-by: argo-rollouts
    argo-rollouts.argoproj.io/strategy: blueGreen

externalSecret:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  remoteRefs:
    databaseUrl:
      key: api-core/prod/DATABASE_URL
    jwtSecret:
      key: api-core/prod/JWT_SECRET
    recoServiceUrl:
      key: api-core/prod/RECO_SERVICE_URL
    logLevel:
      key: api-core/prod/K8S_LOG_LEVEL
    featureFlags:
      key: api-core/prod/K8S_FEATURE_FLAGS
    slackWebhook:
      key: shared/SLACK_WEBHOOK
