{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "api-core.fullname" . }}-secrets
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.secrets.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.databaseUrl.key }}
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.jwtSecret.key }}
    - secretKey: RECO_SERVICE_URL
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.recoServiceUrl.key }}
    - secretKey: K8S_LOG_LEVEL
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.logLevel.key }}
    - secretKey: K8S_FEATURE_FLAGS
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.featureFlags.key }}
    - secretKey: SLACK_WEBHOOK
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.slackWebhook.key }}
{{- end }}
